name: Release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Zip
        run: |
          mkdir OfflineNotify
          mv ./*.lua OfflineNotify/
          mv ./*.xml OfflineNotify/
          mv ./*.txt OfflineNotify/
          mv ./strings OfflineNotify/
          zip -9 OfflineNotify.zip OfflineNotify
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            OfflineNotify.zip